sudo: false
language: python
python:
    - 2.7_with_system_site_packages
    - 3.6_with_system_site_packages

cache:
    - pip
    - apt

addons:
  apt:
    packages:
      - python-dbus
      - python3-dbus

install:
  - pip install -r requirements.txt
  - pip install tox-travis

script:
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)
